import './global.css';
import './app.scss';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Config from '@utils/config';
import HomeLayout from '@layouts/HomeLayout/HomeLayout';
import ToastProvider from '@components/ToastProvider/ToastProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: `${Config.appName}`,
    description: 'Generated by create next app',
};

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <HomeLayout>{children}</HomeLayout>
                <ToastProvider />
            </body>
        </html>
    );
}
